import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import styles from './Layout.module.css'
import {MdBrightnessMedium} from 'react-icons/md'
import Logo from './coronavirus.png'
import Image from "next/image";

const Layout = ({children, title="Covid Analytics"}) => {
    const [theme, setTheme] = useState("dark");
    const switchTheme = () => {
        if(theme === "light")
        {
            setTheme("dark")
            document.documentElement.setAttribute('data-theme', 'dark')
        }
        else
        {
            setTheme("light")
            document.documentElement.setAttribute('data-theme', 'light')
        }
    }
    return(
        <div className={styles.container}>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
                <Link href="/">
                    <div className={styles.header_heading}>
                        <div className={styles.header_heading_image}>
                            <Image src={Logo} quality={70} style={{height:"6vw", width:"6vw"}} alt="Covid-analytics" />
                        </div>
                        <div className={styles.header_heading_title}>
                            <h2><span style={{color:"#b3c5cd"}}>COVID</span> <span style={{color:"#124a63"}}>ANALYTICS</span></h2>
                        </div>
                    </div>
                </Link>
                <button className={styles.themeSwitcher} onClick={switchTheme}>
                    <MdBrightnessMedium/>
                </button>
            </header>
            <main className={styles.main}>
                {children}
            </main>
            <footer className={styles.footer}>
                <p>

            <b>&lt;&#47;&gt;</b> By Priya Jha 
            {/* &#128158;  */}
                </p>
            </footer>
        </div>
    )
}

export default Layout;